<?php

/**
 * @file
 * Module contained miscelanious helper functions and hooks.
 */


/**
 * Implements hook_menu().
 */
function mws_commerce_menu() {
 
  $items['test'] = array(
    'title' => 'Test page',
    'page callback' => 'mws_commerce_testPage',
    'access arguments' => array('administer content'),
    'type' => MENU_CALLBACK,
  ); 

  $items['mws/catalog'] = array(
    'title' => 'Mws catalog page',
    'page callback' => 'mws_commerce_catalogPage',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
  
}


/**
 * Alter commerce_line_item_summary_link_info variable, defined in function commerce_line_item_summary_links()
 * 
 * Replace default url of cart and checkout to redefined ones for a Mws cart block.
 */
function mws_commerce_commerce_line_item_summary_link_info_alter(&$links) {
  $args = arg();
  if (@$args[0] == 'mws' || (@$args[2] == 'views' && (@$args[4] == 'mws_shopping_cart' || @$args[5] == 'mws_shopping_cart'))) {
    if (isset($links['view_cart'])) {
      $links['view_cart']['href'] = 'mws/cart';
    }
    if (isset($links['checkout'])) {
      $links['checkout']['href'] = 'mws/checkout';
    }
  }
}


/**
 * Mws Catalog page.
 */
function mws_commerce_catalogPage() {
  
  global $user;
  $out = NULL;
  
  // Cart block/link.
  // The code was taken from:
  // class commerce_line_item_handler_area_line_item_summary extends views_handler_area {
  // and its function render($empty = FALSE)
  // 
  // Also from here:
  // function commerce_cart_block_view($delta) {
  //
  // And a bit from here:   commerce_line_item_theme()
  $cart_block = 'Your cart is empty';
  if ($order = commerce_cart_order_load($user->uid)) {
      $wrapper = entity_metadata_wrapper('commerce_order', $order);

      // If there are one or more products in the cart...
      if ($quantity = commerce_line_items_quantity($wrapper->commerce_line_items, commerce_product_line_item_types()) > 0) {
        
        $total = commerce_line_items_total($wrapper->commerce_line_items);
        $currency = commerce_currency_load($total['currency_code']);
        $cart_block = '<span>Qty: </span><span>' . $quantity . ' ' . format_plural($quantity, 'item', 'items', array(), array('context' => 'product count on a Commerce order')) . '</span><span>Total: </span><span>' . commerce_currency_format($total['amount'], $total['currency_code']) . '</span><span>' . l('View Cart', 'mws/cart') . '</span><span>' . l('Checkout', 'mws/checkout') . '</span>';
      }
  }
  
  $out .= '<div>' . $cart_block . '</div>';
  
  // Doesn't work.
  //$block_data = array('module' => 'views', 'delta' => 'mws_cart_block');
  //$out .= mws_commerce_getBlockThemed($block_data);
  
  // Works, but we don't really need here a block with the full list of items.
  //$view = views_get_view('mws_shopping_cart');
  //$out .= $view->preview('mws_cart_block');
  
  
  // Render a list of products.
  $tids = array(3 => 3, 4 => 4);
  $display = 'block_products';
 
  $view = views_get_view('catalog_node_siblings');
  $options = array(
    'id' => 'tid',
    'value' => $tids, 
    'type' => 'select',
    'vid' =>  'catalog',
    'hierarchy' => 1,
    'reduce_duplicates' => 1,
    'group' => 0,
  );
  $view->add_item($display, 'filter', 'taxonomy_index', 'tid', $options);

  $out .= $view->preview($display);
  
  return $out;
}


/**
 * Implements hook_form_alter().
 */
function commerce_cart_form_alter(&$form, &$form_state, $form_id) {
  dpm($form_id);
}

/**
 * Test page.
 */
function mws_commerce_testPage() {
  $out = '<div>Test starts</div>';
  
  $out .= '<div>Test ends</div>';
  
  return $out;
}


/**
 * Override or insert variables into the page template.
 */
function mws_commerce_process_page(&$variables) {
  
  if (arg(0) == 'mws') {
    module_invoke('admin_menu', 'suppress');
    $variables['theme_hook_suggestions'][] = 'page__url__mws';
  }
}


/**
 * Implements hook_theme_registry_alter()
**/
function mws_commerce_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'mws_commerce');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('page', 'node');
  foreach ($hooks as $h) {
    _mws_commerce_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}


/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
*/
function _mws_commerce_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}


/**
 * Implements hook_token_info().
 */
function mws_commerce_token_info() {
  // Defines new token 'Provider name' in the node torens group.
  $info['tokens']['node']['node-term-siblings'] = array(
    'name' => t('Node term siblings'),
    'description' => t('First Node siblings'),
  );

  return $info;
}


/**
 * Implements hook_tokens().
 * 
 * Provides token for a current review's provider name. It set to selected from a list or from a manually filled field (if not selected from a list).
 */
function mws_commerce_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);

  // Add new token 'provider-name-for-current-review' to a 'node' tokens group.
  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'node-term-siblings':
          
          $term_children = taxonomy_get_children($node->field_category['und'][0]['taxonomy_term']->tid, $node->field_category['und'][0]['taxonomy_term']->vid);

          $replacements[$original] = '';
          foreach($term_children as $term_child) {
            $replacements[$original] .= ($replacements[$original] ? '+' . $term_child->tid : $term_child->tid);
          }
          
          break;
      }
    }
  }
  
  return $replacements;
}


/**
 * Wrap a block content in proper block's divs.
 */
function mws_commerce_wrapInBlockThemed($block_data, $block)
{
  if(!isset($block['content']) || !$block['content']) {
      return null;
  }
  if (is_array($block['content'])) {
    $block['content'] = render($block);
  }
  
    return 
      '<section id="block-' . $block_data['module'] . '-' . $block_data['delta'] . '" class="block gv block-' . $block_data['module'] . '">' 
         . ( ($block['subject'] && (!isset($block_data['subject_visible']) || $block_data['subject_visible']) )
            ? 
            '<div class="block-icon pngfix"></div><h2 class="block-title">' . $block['subject'] . '</h2>'
            :
            '') 
         . '<div class="content">' . $block['content'] . '</div>
      </section>';
  
}


/**
 * Returns a content of a block wrapped in proper divs.
 */
function mws_commerce_getBlockThemed($block_data)
{
  $block = module_invoke($block_data['module'], 'block_view', $block_data['delta']);
  //dpm($block);
  if ($block) {
    return mws_commerce_wrapInBlockThemed($block_data, $block);
  }
  return NULL;
}